config-version: 2
name: 'netsuite'
version: '0.1.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  netsuite:
    +materialized: table
    +schema: netsuite
    intermediate:
      +materialized: ephemeral

vars:
  netsuite:
    netsuite_account_types: "{{ ref('stg_netsuite__account_types') }}"
    netsuite_accounting_book_subsidiaries: "{{ ref('stg_netsuite__accounting_book_subsidiaries') }}"
    netsuite_accounting_books: "{{ ref('stg_netsuite__accounting_books') }}"
    netsuite_accounting_period_fiscal_calendars: "{{ ref('stg_netsuite__accounting_period_fiscal_calendars') }}"
    netsuite_accounting_periods: "{{ ref('stg_netsuite__accounting_periods') }}"
    netsuite_accounts: "{{ ref('stg_netsuite__accounts') }}"
    netsuite_classes: "{{ ref('stg_netsuite__classes') }}"
    netsuite_consolidated_exchange_rates: "{{ ref('stg_netsuite__consolidated_exchange_rates') }}"
    netsuite_currencies: "{{ ref('stg_netsuite__currencies') }}"
    netsuite_customers: "{{ ref('stg_netsuite__customers') }}"
    netsuite_departments: "{{ ref('stg_netsuite__departments') }}"
    netsuite_entities: "{{ ref('stg_netsuite__entities') }}"
    netsuite_entity_address: "{{ ref('stg_netsuite__entity_address') }}"
    netsuite_items: "{{ ref('stg_netsuite__items') }}"
    netsuite_jobs: "{{ ref('stg_netsuite__jobs') }}"
    netsuite_location_main_address: "{{ ref('stg_netsuite__location_main_address') }}"
    netsuite_locations: "{{ ref('stg_netsuite__locations') }}"
    netsuite_subsidiaries: "{{ ref('stg_netsuite__subsidiaries') }}"
    netsuite_transaction_accounting_lines: "{{ ref('stg_netsuite__transaction_accounting_lines') }}"
    netsuite_transaction_lines: "{{ ref('stg_netsuite__transaction_lines') }}"
    netsuite_transactions: "{{ ref('stg_netsuite__transactions') }}"
    netsuite_vendor_categories: "{{ ref('stg_netsuite__vendor_categories') }}"
    netsuite_vendors: "{{ ref('stg_netsuite__vendors') }}"
    accounts_pass_through_columns: []
    classes_pass_through_columns: []
    consolidated_exchange_rates_pass_through_columns: []
    customers_pass_through_columns: []
    departments_pass_through_columns: []
    employees_pass_through_columns: []
    entities_pass_through_columns: []
    items_pass_through_columns: []
    jobs_pass_through_columns: []
    locations_pass_through_columns: []
    project_tasks_pass_through_columns: []
    subsidiaries_pass_through_columns: []
    time_entries_pass_through_columns: []
    transactions_pass_through_columns: []
    transaction_lines_pass_through_columns: []
    vendors_pass_through_columns: []
    balance_sheet_transaction_detail_columns: []
    income_statement_transaction_detail_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages
